export const posts = [
  {
    title: 'The Maillard Reaction: The Chemistry Behind Perfectly Browned Food',
    description: 'Discover the chemistry behind perfectly seared steaks, golden bread crusts, and rich coffee flavor. Learn how the Maillard reaction transforms your cooking.',
    excerpt: 'Discover the chemistry behind perfectly seared steaks, golden bread crusts, and rich coffee flavor. Learn how the Maillard reaction transforms your cooking through amino acids, sugars, and heat.',
    date: 'February 7, 2026',
    dateISO: '2026-02-07',
    readTime: '9 min read',
    slug: 'maillard-reaction-cooking',
    keywords: ['maillard reaction', 'food chemistry', 'cooking science', 'browning reaction', 'searing steak', 'bread crust', 'coffee roasting', 'amino acids', 'reducing sugars'],
    articleSection: 'Food Chemistry',
    wordCount: 1900,
    dateModified: '2026-02-07',
    faqSchema: [
      { question: 'What is the Maillard reaction?', answer: 'The Maillard reaction is a chemical reaction between amino acids and reducing sugars that occurs when food is heated, typically above 140°C (280°F). It creates hundreds of new flavour and aroma compounds, and is responsible for the browning of bread, seared meat, roasted coffee, and many other foods.' },
      { question: 'Is the Maillard reaction the same as caramelisation?', answer: 'No. Caramelisation involves only sugars heated above their melting point, while the Maillard reaction requires both amino acids and reducing sugars. They often occur together during cooking but are distinct chemical processes that produce different flavour compounds.' },
      { question: 'What temperature does the Maillard reaction occur at?', answer: 'The Maillard reaction becomes significant above 140°C (280°F), which is why boiling (100°C) doesn\'t brown food but frying, roasting, and grilling do. The reaction rate increases with temperature, but very high heat can lead to burning rather than browning.' },
      { question: 'Why does dry food brown better than wet food?', answer: 'Water on the surface of food must evaporate before the temperature can rise above 100°C. Since the Maillard reaction needs temperatures above 140°C, surface moisture prevents browning. This is why patting meat dry before searing produces a better crust.' },
      { question: 'Is the Maillard reaction bad for you?', answer: 'The Maillard reaction itself produces many harmless flavour compounds. However, at very high temperatures or prolonged heating, it can produce acrylamide (mainly in starchy foods like potatoes and bread) and advanced glycation end products (AGEs). Normal cooking produces safe levels, but avoiding charring and extremely high temperatures is a sensible precaution.' },
      { question: 'Why does toast smell so good?', answer: 'When bread is toasted, the Maillard reaction between amino acids and sugars in the flour creates over 540 identified volatile compounds. These include furanones (caramel notes), pyrazines (roasted, nutty notes), and maltol (sweet, baked aroma), which combine to create the distinctive smell of toast.' },
    ],
  },
  {
    title: 'How Do Soaps Work? The Chemistry of Surfactants and Cleaning',
    description: 'Learn how soaps and surfactants work at the molecular level. From saponification to micelle formation, discover the chemistry that makes soap clean—explained by a chemist.',
    excerpt: 'From saponification to micelle formation, discover how soap molecules use their split personality to clean. Learn about surfactants, why hard water causes problems, and the chemistry that makes your hands clean.',
    date: 'February 5, 2026',
    dateISO: '2026-02-05',
    readTime: '14 min read',
    slug: 'how-do-soaps-work',
    keywords: ['soap chemistry', 'surfactants', 'saponification', 'micelles', 'detergents', 'cleaning chemistry', 'amphiphilic molecules'],
    articleSection: 'Chemistry',
    wordCount: 3200,
    dateModified: '2026-02-05',
    faqSchema: [
      { question: 'How does soap actually clean things?', answer: 'Soap molecules have a dual nature: one end is hydrophilic (water-loving) and the other is hydrophobic (water-fearing). When soap meets grease, the hydrophobic tails embed in the oil while the hydrophilic heads face the water. This forms structures called micelles that trap oil droplets and allow them to be rinsed away with water.' },
      { question: 'What is the difference between soap and detergent?', answer: 'Soap is made from natural fats/oils reacted with a strong base (saponification), producing fatty acid salts. Detergents are synthetic surfactants made from petroleum or plant-derived chemicals. Detergents work better in hard water because they don\'t form soap scum (insoluble calcium/magnesium salts).' },
      { question: 'Why doesn\'t soap work well in hard water?', answer: 'Hard water contains calcium and magnesium ions. These react with soap molecules to form insoluble salts (soap scum) instead of cleaning. The calcium and magnesium ions essentially "use up" soap molecules before they can form micelles, reducing cleaning effectiveness and leaving a residue.' },
      { question: 'What is saponification?', answer: 'Saponification is the chemical reaction between a fat or oil (triglyceride) and a strong base like sodium hydroxide (NaOH) or potassium hydroxide (KOH). This reaction breaks the ester bonds in the triglyceride, producing glycerol and fatty acid salts—which are soap. The process typically takes several hours and the soap then needs weeks to cure.' },
      { question: 'Does antibacterial soap work better than regular soap?', answer: 'For everyday handwashing, antibacterial soap is no more effective than regular soap. The FDA banned triclosan and 18 other antibacterial chemicals from consumer soaps in 2016 because manufacturers couldn\'t prove they were more effective than plain soap and water. Regular soap works by physically removing bacteria through the micelle mechanism, not by killing them.' },
      { question: 'What are micelles and how do they form?', answer: 'Micelles are spherical structures that form when soap or surfactant molecules self-assemble in water. Above a concentration called the critical micelle concentration (CMC), the hydrophobic tails cluster together in the centre while the hydrophilic heads face outward toward the water. This creates a tiny sphere that can trap oil and grease inside, allowing it to be washed away.' },
    ],
  },
  {
    title: 'What Are PFAS? The Science Behind Forever Chemicals',
    description: 'Learn what PFAS are, why they\'re called forever chemicals, and what the science says about health risks. Written by a chemist who analysed PFAS in water samples.',
    excerpt: 'PFAS have been found in rainwater worldwide and in the blood of 98% of Americans. Learn what these forever chemicals are, why they persist, and what the science says about health risks—from a chemist who analysed them in the lab.',
    date: 'January 14, 2026',
    dateISO: '2026-01-14',
    readTime: '12 min read',
    slug: 'what-are-pfas',
    keywords: ['PFAS', 'forever chemicals', 'PFAS in drinking water', 'C-F bond', 'PFAS health effects', 'water contamination'],
    articleSection: 'Chemistry',
    wordCount: 2600,
    dateModified: '2026-01-14',
    faqSchema: [
      { question: 'What are PFAS?', answer: 'PFAS (per- and polyfluoroalkyl substances) are a group of over 14,000 synthetic chemicals characterised by strong carbon-fluorine bonds. They\'re used in non-stick coatings, waterproof textiles, food packaging, and firefighting foams. They\'re called "forever chemicals" because the C-F bond is one of the strongest in organic chemistry, making them extremely resistant to degradation.' },
      { question: 'Why are PFAS called forever chemicals?', answer: 'PFAS are called forever chemicals because they contain carbon-fluorine bonds—one of the strongest bonds in organic chemistry (bond energy ~485 kJ/mol). No natural environmental process can break these bonds efficiently. Some PFAS have estimated environmental half-lives of over 1,000 years, meaning they accumulate in the environment and in living organisms over time.' },
      { question: 'Are PFAS dangerous to human health?', answer: 'Research has linked PFAS exposure to several health effects including thyroid disruption, liver damage, immune system suppression (including reduced vaccine efficacy), increased cholesterol levels, and increased risk of certain cancers (particularly kidney and testicular). However, the health effects of most individual PFAS compounds remain understudied, as the vast majority of the 14,000+ compounds haven\'t been individually tested.' },
      { question: 'How do PFAS get into drinking water?', answer: 'PFAS enter drinking water primarily through industrial discharge, use of PFAS-containing firefighting foams (AFFF) at military bases and airports, landfill leachate, and wastewater treatment plants (which can\'t fully remove PFAS). Once in groundwater, they persist indefinitely and can travel long distances through aquifers.' },
      { question: 'Can you remove PFAS from water?', answer: 'Yes, but standard water treatment doesn\'t remove PFAS effectively. Proven removal methods include granular activated carbon (GAC), ion exchange resins, and reverse osmosis/nanofiltration membranes. Point-of-use filters certified for PFAS removal (NSF/ANSI 53 or 58) can reduce levels in drinking water at home. However, these methods concentrate PFAS into waste streams that still require disposal.' },
      { question: 'What products contain PFAS?', answer: 'PFAS are found in non-stick cookware (Teflon/PTFE), waterproof and stain-resistant clothing and textiles (Gore-Tex), food packaging (microwave popcorn bags, fast food wrappers), firefighting foams (AFFF), some cosmetics and personal care products, dental floss, ski wax, and many industrial applications. Not all products in these categories contain PFAS, and many manufacturers are transitioning to PFAS-free alternatives.' },
    ],
  },
  {
    title: 'What Are Terpenes? The Chemistry Behind How Things Smell',
    description: 'Learn what terpenes are, how they create smells, and why they matter. From limonene to pinene, discover the chemistry behind scents in nature.',
    excerpt: 'From pine forests to citrus peels, terpenes create the smells around you. Learn what terpenes are, how they work, and why limonene smells like oranges while its mirror image smells like lemons.',
    date: 'January 13, 2026',
    dateISO: '2026-01-13',
    readTime: '8 min read',
    slug: 'what-are-terpenes',
    keywords: ['terpenes', 'terpenoids', 'limonene', 'pinene', 'linalool', 'essential oils', 'olfactory chemistry'],
    articleSection: 'Chemistry',
    wordCount: 2400,
    dateModified: '2026-01-14',
    faqSchema: [
      { question: 'What are terpenes?', answer: 'Terpenes are a large class of organic compounds produced by plants, built from repeating five-carbon isoprene units (C₅H₈). They\'re responsible for the distinctive smells of plants—limonene gives citrus its scent, pinene gives pine trees their smell, and linalool gives lavender its aroma. Over 30,000 terpenes have been identified in nature.' },
      { question: 'What is the difference between terpenes and terpenoids?', answer: 'Terpenes are pure hydrocarbons made only of carbon and hydrogen, built from isoprene units. Terpenoids (also called isoprenoids) are modified terpenes that contain additional functional groups like oxygen. For example, menthol is a terpenoid—it\'s based on a terpene skeleton but has a hydroxyl (-OH) group added. In casual usage, "terpenes" often refers to both.' },
      { question: 'Why do terpenes smell?', answer: 'Terpenes are small, volatile molecules that easily evaporate at room temperature. When they reach your nose, they bind to olfactory receptors—each terpene\'s unique 3D shape fits specific receptors, triggering nerve signals your brain interprets as distinct smells. Even mirror-image molecules (enantiomers) can smell different: (R)-limonene smells like oranges while (S)-limonene smells like lemons.' },
      { question: 'Why do plants produce terpenes?', answer: 'Plants produce terpenes primarily for defence and communication. They repel herbivores and parasites, attract pollinators and seed dispersers, protect against UV radiation and oxidative stress, and signal to neighbouring plants about threats. Some terpenes also have antimicrobial properties that protect plants from fungal and bacterial infections.' },
      { question: 'Are terpenes safe?', answer: 'Most terpenes are generally recognised as safe (GRAS) by the FDA for food use. We consume them daily in fruits, vegetables, herbs, and spices. However, concentrated essential oils containing high levels of terpenes can cause skin irritation, allergic reactions, or toxicity if ingested in large amounts. As with any chemical, the dose determines safety.' },
    ],
    imageSchemas: [
      {
        '@type': 'ImageObject',
        contentUrl: 'https://mileschristou.co.uk/blog/terpene-isoprene.svg',
        name: 'Isoprene Unit Structure',
        description: 'The molecular structure of isoprene (2-methylbuta-1,3-diene), the fundamental C₅H₈ building block from which all terpenes are constructed.',
        caption: 'Isoprene (C₅H₈) — the five-carbon building block of all terpenes.',
      },
      {
        '@type': 'ImageObject',
        contentUrl: 'https://mileschristou.co.uk/blog/terpene-structures-improved.png',
        name: 'Common Terpene Structures',
        description: 'Chemical structures of six common terpenes: limonene, pinene, myrcene, linalool, menthol, and geraniol, showing their molecular geometry and functional groups.',
        caption: 'Structures of six common terpenes found in nature, from the citrus scent of limonene to the cooling sensation of menthol.',
      },
    ],
  },
  {
    title: 'How is Coffee Decaffeinated? The Science Behind Your Decaf',
    description: 'Learn how coffee is decaffeinated using Swiss Water, CO₂, and solvent methods. Chemistry-backed guide to decaf processes, safety, and flavour.',
    excerpt: 'Discover the chemistry behind decaf coffee. Learn about Swiss Water Process, supercritical CO₂, and solvent methods in this complete guide to decaffeination.',
    date: 'January 11, 2026',
    dateISO: '2026-01-11',
    readTime: '10 min read',
    slug: 'decaf-coffee-science',
    keywords: ['decaf coffee', 'decaffeination', 'Swiss Water Process', 'supercritical CO2', 'caffeine removal', 'coffee chemistry'],
    articleSection: 'Chemistry',
    wordCount: 2200,
    dateModified: '2026-01-11',
    faqSchema: [
      { question: 'How is coffee decaffeinated?', answer: 'Coffee is decaffeinated using one of four main methods: the Swiss Water Process (uses water and activated carbon), supercritical CO₂ extraction (uses pressurised carbon dioxide), or solvent-based methods using either methylene chloride or ethyl acetate. All methods work on green (unroasted) beans and exploit caffeine\'s solubility to selectively remove it while preserving flavour compounds.' },
      { question: 'Is decaf coffee completely caffeine-free?', answer: 'No. Decaf coffee still contains small amounts of caffeine—typically 2-15mg per cup compared to 80-100mg in regular coffee. This represents about 97% caffeine removal. The exact amount varies by method, bean type, and brewing technique. For most people, this residual caffeine is insignificant, but those with extreme caffeine sensitivity should be aware.' },
      { question: 'Is decaf coffee safe to drink?', answer: 'Yes. All approved decaffeination methods produce safe coffee. Solvent-based methods use chemicals (methylene chloride or ethyl acetate) that evaporate almost entirely during roasting—residual levels are far below safety limits set by the FDA. The Swiss Water Process and CO₂ method use no organic solvents at all. Multiple studies confirm decaf coffee is safe for regular consumption.' },
      { question: 'What is the Swiss Water Process?', answer: 'The Swiss Water Process is a chemical solvent-free decaffeination method. Green coffee beans are soaked in hot water saturated with coffee flavour compounds (called Green Coffee Extract or GCE). Because the water is already saturated with flavour compounds but not caffeine, only caffeine migrates out of the beans. The caffeine is then removed from the water using activated carbon filters, and the water is reused.' },
      { question: 'Does decaf coffee taste different from regular coffee?', answer: 'Decaf coffee can taste slightly different because caffeine itself contributes bitterness, and the decaffeination process can remove some volatile flavour compounds alongside caffeine. However, modern methods—especially supercritical CO₂ and Swiss Water Process—preserve most flavour compounds. The biggest factor in taste is usually the quality of the beans and roasting, not the decaffeination method.' },
    ],
    imageSchemas: [
      {
        '@type': 'ImageObject',
        contentUrl: 'https://mileschristou.co.uk/blog/caffeine-molecule.svg',
        name: 'Caffeine Molecule Structure',
        description: 'The molecular structure of caffeine (1,3,7-trimethylxanthine), showing its purine ring system and three methyl groups that make it soluble in both water and organic solvents.',
        caption: 'Caffeine (C₈H₁₀N₄O₂) — the molecule that decaffeination targets.',
      },
      {
        '@type': 'ImageObject',
        contentUrl: 'https://mileschristou.co.uk/blog/decaf-process-flow.svg',
        name: 'Decaffeination Methods Comparison',
        description: 'A visual comparison of the four main decaffeination methods: Swiss Water Process, supercritical CO₂, methylene chloride, and ethyl acetate, showing the key steps in each process.',
        caption: 'Overview of the four main commercial decaffeination methods.',
      },
      {
        '@type': 'ImageObject',
        contentUrl: 'https://mileschristou.co.uk/blog/swiss-water-process.svg',
        name: 'Swiss Water Process Diagram',
        description: 'Detailed diagram of the Swiss Water Process showing how green coffee extract (GCE) selectively removes caffeine from coffee beans without organic solvents.',
        caption: 'The Swiss Water Process uses water saturated with coffee compounds to selectively extract caffeine.',
      },
      {
        '@type': 'ImageObject',
        contentUrl: 'https://mileschristou.co.uk/blog/supercritical-co2.svg',
        name: 'Supercritical CO₂ Extraction Diagram',
        description: 'Diagram showing how supercritical carbon dioxide (above 31°C and 74 atm) selectively dissolves and removes caffeine from green coffee beans in a high-pressure extraction vessel.',
        caption: 'Supercritical CO₂ extraction — caffeine dissolves into pressurised carbon dioxide above its critical point.',
      },
    ],
  },
];

export function getPostBySlug(slug) {
  return posts.find((post) => post.slug === slug);
}

export function getAllSlugs() {
  return posts.map((post) => post.slug);
}
